### ISSUE TITLE
Limit dag run history by number of runs

### ISSUE THREAD

**Issue by ghansham** [dagucloud/dagu#1069]
Currently dagu limits history for dag run by number of days by defining configuration at global level via base.yaml or individual dag levels. This feature is very useful for cron jobs. For non cron jobs, it may never get used. For non cron jobs, the history of dag runs should be limited by the number of runs rather than number of days.

As suggested by @yottahmd, we can add something like this:
```yaml
historyRetention:
  runs: 3 # Limit by runs
  days: 5 # Limit by days
```

**Comment by yohamta0** [comment]
Thank you for submitting the issue. Here’s a proposed design with minimal changes:
```yaml
# keep the last 5 runs
historyRetentionRuns: 5

# keep for the last 5 days (already supported)
historyRetentionDays: 5
```
It should result in validation error when both specified.

To-Do:
- Implement `historyRetentionRuns` field and clean up logic
- Add unit tests
- Update documentation
- Update json schema
