### ISSUE TITLE
DAG history of in-progress execution doesn't show currently running step

### ISSUE THREAD

**Issue by fishnux** [dagucloud/dagu#468]
DAG history of in-progress execution doesn't show currently running step

DAG status: (route: /dags/mydag)
<img width="120" alt="imagem" src="https://github.com/dagu-dev/dagu/assets/29991194/2d12b00f-c3e0-4587-a3b9-af50010ea07d">

DAG history: (route: /dags/mydag/history)
<img width="112" alt="imagem" src="https://github.com/dagu-dev/dagu/assets/29991194/607ce40c-6aa7-4ed9-b3ea-588d20dc2021">

Example DAG:
```
steps:
  - name: sleep
    command: "sleep 1"
  - name: sleep2
    command: "sleep 30"
  - name: sleep3
    command: "sleep 30"
```
