### ISSUE TITLE
bug: container runner produces no stdout

### ISSUE THREAD

**Issue by bagemt** [dagucloud/dagu#967]
[v1.17.0-beta.2](https://github.com/dagu-org/dagu/releases/tag/v1.17.0-beta.2)

example tasks

```yaml
  - name: hello
    executor:
      type: docker
      config:
        image: alpine
        autoRemove: true
        pull: false
        host:
          binds:
            - /runners/cache:/cache:rw
    shell: bash
    script: |
      echo "hello"
      ls -al /cache

  - name: platform test
    executor:
      type: docker
      config:
        image: alpine
        autoRemove: true
        pull: always
        platform: linux/arm64
    command: uname -m
    depends: hello
```

**Comment by yottahmd** [comment]
Thanks for reporting the issue! Will look into this.

**Comment by yohamta0** [comment]
@bagemt Currently, docker executor does not support `script` field. Could you try something like this?
```yaml
steps:
  - name: hello
    executor:
      type: docker
      config:
        image: alpine
        autoRemove: true
        pull: false
        host:
          binds:
            - /runners/cache:/cache:rw
    command: ls -al /cache
```

**Comment by bagemt** [comment]
@yottahmd You meant `command` instead of `shell`, right? In beta 4 `command` works (at least kind of), for `shell`

```yaml
shell: ls -al /cache

Failed to execute dag-run" dag=test dagRunId=01972aa7-16a4-70e7-891b-6298d3db1b76 err="failed to execute step \"hello\": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: \"ls -al /cache\": stat ls -al /cache: no such file or directory
```

Found several issues that affect only the container runner, **work** as expected on the native

- stderr also doesn't get populated and shell redirection does not work, always gets printed to stdout

```yaml
command: |
  echo "Error: Something went wrong" >&2
command: |
  echo "This message goes to stderr" 1>&2
```

- container environment variable expansion is also broken, `$` gets escaped

```yaml
command: echo $0 && ps -p $$
```

- running shell with options is does not work

```yaml
command: /bin/bash -o errexit -o xtrace -o pipefail -c "echo 'hello world' && ls -al /"
``` 

For all runner, for `shell: ` it doesn't  make sense it cannot accept shell options, you can give the in other ways but this is cleaner

```yaml
  # works
  - name: step1
    description: test step
    command: /bin/bash -o errexit -o xtrace -o pipefail -c "echo 'hello world' && ls -al /"
    shell: bash

  # works
  - name: step2
    command: /bin/bash -o errexit -o xtrace -o pipefail -c
    script: |
      echo $TEST
      ls -al /
      ls -al .

 # doesn't work
  - name: step3
    description: test step
    command: echo 'hello world' && ls -al /
    shell: /bin/bash -o errexit -o xtrace -o pipefail -c
```

Should I open separate issues for those?

**Comment by yohamta0** [comment]
> You meant command instead of shell, right? In beta 4 command works (at least kind of), for shell
Yes, that's correct.

Thank you for pointing out these issues! Regarding the command executor, it has been fixed in beta 5 to properly handle shell options.

As for the Docker executor, I’m still considering what the correct behavior should be. I need to do some research on the best way to handle arguments like `$` variables. Any suggestions would be greatly appreciated!

**Comment by bagemt** [comment]
> Regarding the command executor, it has been fixed in beta 5 to properly handle shell options.

Confirming it's fixed

> As for the Docker executor, I’m still considering what the correct behavior should be. I need to do some research on the best way to handle arguments like $ variables. Any suggestions would be greatly appreciated!

IMO we can do what `docker compose` does. Or maybe not.

There are several variable expansions to think about: 

1. container entrypoint - entrypoint processing the variables
    - Shell - variables expanded by shell/interactive shell (depending on the run as user .bashrc/.zshrc...)
    - container image - env. variables provided by the Dockerfile ENV and ARGS during build time
2. docker/podman run `command` and docker compose bare `command:`  not passed for evaluation by entrypoint or shell

    ```yaml
    docker run image:tag command
    podman run image:tag command
    ```
     `command` is evaluated by the entrypoint if available from the image or run as bare command. for example `/usr/bin/ls -al /` is run without shell or entry point evaluation if the image Dockerfile does not contain `ENTRYPOINT`

3. executor `env:` (container engine env)
    ```yaml
      - name: step1
        executor:
          type: docker
          config:
            exec:
              env:
                - MY_VAR=value
    ```

4. dagu variable expansion from previous task `output:`, dag level `env:` and parent dag `params:`


 ---
In all cases `$VAR` and `${VAR}` should be expanded if available depending on the context it comes from. The actual expansion should be left to the container engine instead be done by dagu. Or it can be configurable, so that one option is all variables are expanded by dagu before being passed to the executor or all variable are passed as it is and is up to the container engine to expand them using the entrypoint and the `env` vars. ,Given

```yaml
    command: echo "Hello from existing container ${MY_VAR}"
```

example variable precedence for `MY_VAR`, higher -> lower

```bash
4. -> 3. -> 1.
```

meaning if `4.` exist it overwrites `3.` and `1.`... if None exist expand to `""`

variables from `4.` can be added on runtime to executor `env:`, replace existing if same name already in `env:`

```yaml
- name: step1
  executor:
    type: docker
    config:
      exec:
        env:
```

If `4.` or `3.` do not exist and the variable comes from shell config or container image it gets evaluated by container entrypoint. If no entrypoint exists there are 3 ways to set one:

```yaml
# docker native way
- name: step1
  executor:
    type: docker
    config:
      entrypoint: /bin/bash -c

# same as above, internally it sets `entrypoint:` from `shell:`
- name: step1
  executor:
    type: docker
 shell: /bin/bash -o errexit -o xtrace -o pipefail -c

# the command itself is executed by the given shell/interpreter (eg. python...) equivalent to 2.
- name: step1
  executor:
    type: docker
 command: /bin/bash -o errexit -o xtrace -o pipefail -c 'echo "Hello from existing container ${MY_VAR}"'
```

Might require some more thinking but this is a rough idea

---

found more issues - `run as user` does not change the user, it always runs as root

```yaml
- name: step1
  executor:
    type: docker
    config:
      image: local-registry.io/alpine
      autoRemove: true
      pull: false
      exec:
        user: notroot:notroot
  command: id
```

and container env vars do not get evaluated

```yaml
- name: step1
  executor:
    type: docker
    config:
      image: local-registry.io/alpine
      autoRemove: true
      pull: false
      entrypoint: /bin/bash -c
      exec:
        env:
          - MY_VAR=value
  command: echo "Hello from existing container ${MY_VAR}"
```

I feel like executor config should closely 1:1 match the docker, and in the future podman api behaviour and maybe have some test for validation

**Comment by yohamta0** [comment]
Thanks for the detailed analysis! I'm working on the docker executor stdout issue reported in #965.
Following docker-compose's approach is a great idea. The comprehensive design you've provided all looks good to me. Let's go with this approach.

**Comment by jerry-yuan** [comment]
@yottahmd Hey! I just discovered a weird phenomenon: the node logs with pure alphabet characters output normally, but the logs containing Chinese characters are missing.  

I briefly looked at the log handling in the Docker executor—it seems to use official Docker methods. I’ll try debugging the `dagu start` command when I have time later.

**Comment by yohamta0** [comment]
@jerry-yuan Thank you so much for discovering the issue! Agreed that it's a weird phenomenon. I've also found some issues in the docker executor and just fixed them in v1.17.0-beta.7. Could you please try with the latest image to see if it's still happening?

**Comment by jerry-yuan** [comment]
@yottahmd Unfortunately, it still not working.

![Image](https://github.com/user-attachments/assets/59d10617-1ac9-40f9-943e-4246fae11d51)

![Image](https://github.com/user-attachments/assets/254871ef-d284-487a-aba6-8e329b4044be)

**Comment by yohamta0** [comment]
@jerry-yuan Could I ask what you expect to be written to stderr in your setup? I tested the following DAG and it seemed to work fine on my end. Could you please check if this works for you?

```yaml
steps:
  - name: run
    executor:
      type: docker
      config:
        image: "alpine:latest"
        pull: always
        autoRemove: true
    command: sh -c 'echo write to stdout; echo write to stderr >&2'
```
